In [3]:
l1=[1,2,34,5]
l1.extend([12,4,67.7,54])

In [4]:
l1

[1, 2, 34, 5, 12, 4, 67.7, 54]

In [5]:
l1[::-1]

[54, 67.7, 4, 12, 5, 34, 2, 1]

In [6]:
l1[::2]

[1, 34, 12, 67.7]

In [7]:
l1[::-2]

[54, 4, 5, 2]

In [8]:
#intro to numpy example problem to calc bmi
height=[1.73,1.68,1.71,1.89,1.79]
weight=[65.4,59.2,63.6,88.4,68.7]
import numpy as np
np_height=np.array(height)
np_weight=np.array(weight)
bmi=np_weight/np_height**2


In [9]:
bmi

array([21.85171573, 20.97505669, 21.75028214, 24.7473475 , 21.44127836])

In [10]:
np.array([1,85.2,True])

array([ 1. , 85.2,  1. ])

In [12]:
np.array([35,'yes',65.3])

array(['35', 'yes', '65.3'], dtype='<U21')

In [13]:
bmi[2]

21.750282138093777

In [14]:
type(bmi)

numpy.ndarray

In [15]:
bmi>21


array([ True, False,  True,  True,  True])

In [18]:
bmi[bmi>23]

array([24.7473475])

In [19]:
sai=bmi>23

In [20]:
sai

array([False, False, False,  True, False])

In [21]:
sai2=bmi[bmi>21]

In [22]:
sai2

array([21.85171573, 21.75028214, 24.7473475 , 21.44127836])

In [23]:
np.array([True, 1, 2]) + np.array([3, 4, False])


array([4, 5, 2])

In [24]:
l1=[[1,2,3,4,5],[6,7,8,9,10],[11,12,13,14,15],[16,17,18,19,20]]
np_li=np.array(l1)

In [25]:
np_li

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [26]:
np_li[1:,1:4]

array([[ 7,  8,  9],
       [12, 13, 14],
       [17, 18, 19]])

In [29]:
import numpy as np
np_mat = np.array([[1, 2],
                   [3, 4],
                   [5, 6]])
print(np_mat * 2)
print(np_mat + np.array([20]))
print(np_mat + np.array([10,20]))
print(np_mat + np_mat)

conversion = np.array([0.0254,0.453592,1])
# Print out product of np_baseball and conversion
print(np_baseball * conversion)

[[ 2  4]
 [ 6  8]
 [10 12]]
[[21 22]
 [23 24]
 [25 26]]
[[11 22]
 [13 24]
 [15 26]]
[[ 2  4]
 [ 6  8]
 [10 12]]
